import 'dart:math';
import 'dart:ui';

import 'package:action/components/poster.dart';
import 'package:action/components/poster_tile.dart';
import 'package:action/person.dart';
import 'package:flutter/material.dart';

const details = {
  "adult": false,
  "backdrop_path": "/m8JTwHFwX7I7JY5fPe4SjqejWag.jpg",
  "belongs_to_collection": {
    "id": 422834,
    "name": "Ant-Man Collection",
    "poster_path": "/qxMs5TU6zOTQ7cbmBZ6xGvHUDa2.jpg",
    "backdrop_path": "/2KjtWUBiksmN8LsUouaZnxocu5N.jpg"
  },
  "budget": 200000000,
  "genres": [
    {"id": 28, "name": "Action"},
    {"id": 12, "name": "Adventure"},
    {"id": 878, "name": "Science Fiction"}
  ],
  "homepage": "https://www.marvel.com/movies/ant-man-and-the-wasp-quantumania",
  "id": 640146,
  "imdb_id": "tt10954600",
  "original_language": "en",
  "original_title": "Ant-Man and the Wasp: Quantumania",
  "overview":
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
  "popularity": 281.343,
  "poster_path": "/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg",
  "production_companies": [
    {
      "id": 420,
      "logo_path": "/hUzeosd33nzE5MCNsZxCGEKTXaQ.png",
      "name": "Marvel Studios",
      "origin_country": "US"
    },
    {
      "id": 176762,
      "logo_path": null,
      "name": "Kevin Feige Productions",
      "origin_country": "US"
    }
  ],
  "production_countries": [
    {"iso_3166_1": "US", "name": "United States of America"}
  ],
  "release_date": "2023-02-15",
  "revenue": 475766228,
  "runtime": 125,
  "spoken_languages": [
    {"english_name": "English", "iso_639_1": "en", "name": "English"}
  ],
  "status": "Released",
  "tagline": "Witness the beginning of a new dynasty.",
  "title": "Ant-Man and the Wasp: Quantumania",
  "video": false,
  "vote_average": 6.46,
  "vote_count": 3784,
  "credits": {
    "cast": [
      {
        "adult": false,
        "gender": 2,
        "id": 22226,
        "known_for_department": "Acting",
        "name": "Paul Rudd",
        "original_name": "Paul Rudd",
        "popularity": 55.248,
        "profile_path": "/1xBl6m2cpsm4EcAgIDmVqlKDvNK.jpg",
        "cast_id": 1,
        "character": "Scott Lang / Ant-Man",
        "credit_id": "5da88f43a2423200177bf176",
        "order": 0
      },
      {
        "adult": false,
        "gender": 1,
        "id": 19034,
        "known_for_department": "Acting",
        "name": "Evangeline Lilly",
        "original_name": "Evangeline Lilly",
        "popularity": 65.853,
        "profile_path": "/eX24uZ023VifIoid4FyEUALl6Fm.jpg",
        "cast_id": 2,
        "character": "Hope van Dyne / The Wasp",
        "credit_id": "5da88f59944a570019264e0e",
        "order": 1
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1674162,
        "known_for_department": "Acting",
        "name": "Jonathan Majors",
        "original_name": "Jonathan Majors",
        "popularity": 16.373,
        "profile_path": "/nsxnMbkl9Lpc12AmYwKi9SmsJ7e.jpg",
        "cast_id": 19,
        "character": "Kang the Conqueror",
        "credit_id": "5f5f98bd93388b00365dfff9",
        "order": 2
      },
      {
        "adult": false,
        "gender": 1,
        "id": 221192,
        "known_for_department": "Acting",
        "name": "Kathryn Newton",
        "original_name": "Kathryn Newton",
        "popularity": 46.416,
        "profile_path": "/hEz2R1RTgaNznJ3fa9n3KabIXYl.jpg",
        "cast_id": 20,
        "character": "Cassie Lang",
        "credit_id": "5fd2c49118b7510041901e78",
        "order": 3
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1160,
        "known_for_department": "Acting",
        "name": "Michelle Pfeiffer",
        "original_name": "Michelle Pfeiffer",
        "popularity": 26.211,
        "profile_path": "/oGUmQBU87QXAsnaGleYaAjAXSlj.jpg",
        "cast_id": 15,
        "character": "Janet van Dyne",
        "credit_id": "5dbf376defe37c001383ed0d",
        "order": 4
      },
      {
        "adult": false,
        "gender": 2,
        "id": 3392,
        "known_for_department": "Acting",
        "name": "Michael Douglas",
        "original_name": "Michael Douglas",
        "popularity": 16.028,
        "profile_path": "/kVYGPIZowzXLEQfAGUNOqKjAbBb.jpg",
        "cast_id": 16,
        "character": "Dr. Hank Pym",
        "credit_id": "5dbf3786f1b5710010e7221c",
        "order": 5
      },
      {
        "adult": false,
        "gender": 2,
        "id": 74541,
        "known_for_department": "Acting",
        "name": "Corey Stoll",
        "original_name": "Corey Stoll",
        "popularity": 22.931,
        "profile_path": "/etqmosIyf1xePKpi3i6rHJCm9GE.jpg",
        "cast_id": 59,
        "character": "M.O.D.O.K.",
        "credit_id": "63bd1814fa404600e63c03e1",
        "order": 6
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1532,
        "known_for_department": "Acting",
        "name": "Bill Murray",
        "original_name": "Bill Murray",
        "popularity": 17.479,
        "profile_path": "/nnCsJc9x3ZiG3AFyiyc3FPehppy.jpg",
        "cast_id": 34,
        "character": "Lord Krylar",
        "credit_id": "6178879871f095008b820108",
        "order": 7
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1410478,
        "known_for_department": "Acting",
        "name": "William Jackson Harper",
        "original_name": "William Jackson Harper",
        "popularity": 5.13,
        "profile_path": "/5Oy037YttIweiqNGaErkalNmH0G.jpg",
        "cast_id": 44,
        "character": "Quaz",
        "credit_id": "635b3856fd63000079a81c20",
        "order": 8
      },
      {
        "adult": false,
        "gender": 2,
        "id": 83854,
        "known_for_department": "Acting",
        "name": "David Dastmalchian",
        "original_name": "David Dastmalchian",
        "popularity": 32.984,
        "profile_path": "/o9oOnTUbsFVYzifDZDdwrsAidy8.jpg",
        "cast_id": 47,
        "character": "Veb (voice)",
        "credit_id": "6383d138bf09d100afd151c9",
        "order": 9
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1530151,
        "known_for_department": "Acting",
        "name": "Jamie Andrew Cutler",
        "original_name": "Jamie Andrew Cutler",
        "popularity": 3.506,
        "profile_path": "/xQnGZh5WGiD3LRAM47tMpU6eRZr.jpg",
        "cast_id": 62,
        "character": "XOLUM",
        "credit_id": "63e14cd9629b2c007f850c0e",
        "order": 10
      },
      {
        "adult": false,
        "gender": 1,
        "id": 2252989,
        "known_for_department": "Acting",
        "name": "Katy O'Brian",
        "original_name": "Katy O'Brian",
        "popularity": 24.673,
        "profile_path": "/73ygY0oDNtkd0thdpCY6idspmzg.jpg",
        "cast_id": 48,
        "character": "Jentorra",
        "credit_id": "6383fc49229ae21572a8f332",
        "order": 11
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1602424,
        "known_for_department": "Acting",
        "name": "Mark Weinman",
        "original_name": "Mark Weinman",
        "popularity": 0.6,
        "profile_path": "/ljG1caFhz0I6NH8qwwxSI7XEnse.jpg",
        "cast_id": 70,
        "character": "Patrol Police Officer / On-Set M.O.D.O.K.",
        "credit_id": "63e1a121cb80280093e68a5c",
        "order": 12
      },
      {
        "adult": false,
        "gender": 2,
        "id": 79082,
        "known_for_department": "Acting",
        "name": "Randall Park",
        "original_name": "Randall Park",
        "popularity": 19.11,
        "profile_path": "/1QJ4cBQZoOaLR8Hc3V2NgBLvB0f.jpg",
        "cast_id": 41,
        "character": "Jimmy Woo",
        "credit_id": "631cdbd5d399e6008485c6f1",
        "order": 13
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1126237,
        "known_for_department": "Acting",
        "name": "Ross Mullan",
        "original_name": "Ross Mullan",
        "popularity": 2.116,
        "profile_path": "/zGMN6r58cOZMef3vLk8onxlOHwj.jpg",
        "cast_id": 71,
        "character": "Axia Restaurant Maitre D'",
        "credit_id": "63e1a131c8a2d400d4ffeefe",
        "order": 14
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2677070,
        "known_for_department": "Acting",
        "name": "Tom Clark",
        "original_name": "Tom Clark",
        "popularity": 0.77,
        "profile_path": "/wYQkvbOeiFsNdSjaolyX6ovJPVa.jpg",
        "cast_id": 209,
        "character": "Axia Restaurant Bartender",
        "credit_id": "63f28092a6725400d7c8b970",
        "order": 15
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1234382,
        "known_for_department": "Acting",
        "name": "Leon Cooke",
        "original_name": "Leon Cooke",
        "popularity": 1.799,
        "profile_path": "/2ltoe0Ue76EAO0u1D9KbNjj60Kg.jpg",
        "cast_id": 73,
        "character": "Axia Restaurant Bartender",
        "credit_id": "63e1a143cb80280093e68a9b",
        "order": 16
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909113,
        "known_for_department": "Acting",
        "name": "Nathan Blees",
        "original_name": "Nathan Blees",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 74,
        "character": "Axia Restaurant Waiter",
        "credit_id": "63e1a154cb802800a1a519d7",
        "order": 17
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3243391,
        "known_for_department": "Acting",
        "name": "Durassie Kiangangu",
        "original_name": "Durassie Kiangangu",
        "popularity": 0.656,
        "profile_path": null,
        "cast_id": 75,
        "character": "Axia Restaurant Waiter",
        "credit_id": "63e1a166528b2e00e76fe0dd",
        "order": 18
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1972102,
        "known_for_department": "Acting",
        "name": "Liran Nathan",
        "original_name": "Liran Nathan",
        "popularity": 1.054,
        "profile_path": "/4pcKpaZkqObqhkOpkkv7qIOfmZh.jpg",
        "cast_id": 76,
        "character": "Axia Restaurant Waiter",
        "credit_id": "63e1a16e77394100aa291e1e",
        "order": 19
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909124,
        "known_for_department": "Acting",
        "name": "Sam Symons",
        "original_name": "Sam Symons",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 77,
        "character": "Krylar's Valet",
        "credit_id": "63e1a187cb8028007b6c1d79",
        "order": 20
      },
      {
        "adult": false,
        "gender": 2,
        "id": 662006,
        "known_for_department": "Acting",
        "name": "Grahame Fox",
        "original_name": "Grahame Fox",
        "popularity": 1.589,
        "profile_path": "/sGn6CPIpnVA9HKd6TvDbBM5ja5r.jpg",
        "cast_id": 78,
        "character": "Broccoli Man",
        "credit_id": "63e1a18fcb8028007b6c1d8d",
        "order": 21
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909128,
        "known_for_department": "Acting",
        "name": "Nicola Peluso",
        "original_name": "Nicola Peluso",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 79,
        "character": "Corrections Officer",
        "credit_id": "63e1a1ab7776f0008c45b804",
        "order": 22
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3861486,
        "known_for_department": "Acting",
        "name": "Harrison Daniels",
        "original_name": "Harrison Daniels",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 80,
        "character": "Booking Officer",
        "credit_id": "63e1a1b577394100aa291e8a",
        "order": 23
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909135,
        "known_for_department": "Acting",
        "name": "Brahmdeo Shannon Ramana",
        "original_name": "Brahmdeo Shannon Ramana",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 81,
        "character": "Hope's Assistant",
        "credit_id": "63e1a1e7cb80280093e68b8c",
        "order": 24
      },
      {
        "adult": false,
        "gender": 2,
        "id": 937222,
        "known_for_department": "Acting",
        "name": "Russell Balogh",
        "original_name": "Russell Balogh",
        "popularity": 5.008,
        "profile_path": "/fMQ4y0ebqBfrOuKj3Y0RKEjEi63.jpg",
        "cast_id": 82,
        "character": "Nomad Leader",
        "credit_id": "63e1a1fcac8e6b00a0b9e3a4",
        "order": 25
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3757664,
        "known_for_department": "Acting",
        "name": "Leonardo Taiwo",
        "original_name": "Leonardo Taiwo",
        "popularity": 0.612,
        "profile_path": null,
        "cast_id": 83,
        "character": "Quantumnaut Scientist",
        "credit_id": "63e1a207ac8e6b00849929df",
        "order": 26
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2595392,
        "known_for_department": "Acting",
        "name": "Osian Roberts",
        "original_name": "Osian Roberts",
        "popularity": 0.851,
        "profile_path": null,
        "cast_id": 84,
        "character": "Quantumnaut Lieutenant",
        "credit_id": "63e1a214ac8e6b008edcee63",
        "order": 27
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909141,
        "known_for_department": "Acting",
        "name": "Lucas Gerstel",
        "original_name": "Lucas Gerstel",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 85,
        "character": "Book Signing Audience",
        "credit_id": "63e1a227cb80280093e68bd2",
        "order": 28
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909142,
        "known_for_department": "Acting",
        "name": "Mia Gerstel",
        "original_name": "Mia Gerstel",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 86,
        "character": "Book Signing Audience",
        "credit_id": "63e1a22ec8a2d400d4fff044",
        "order": 29
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909144,
        "known_for_department": "Acting",
        "name": "Tracy Jeffrey",
        "original_name": "Tracy Jeffrey",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 87,
        "character": "Book Signing Audience",
        "credit_id": "63e1a246cb80280093e68bfe",
        "order": 30
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909145,
        "known_for_department": "Acting",
        "name": "Dinah Jeffrey",
        "original_name": "Dinah Jeffrey",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 88,
        "character": "Book Signing Audience",
        "credit_id": "63e1a257c8a2d400ab2b1e72",
        "order": 31
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909146,
        "known_for_department": "Acting",
        "name": "Judy Jeffrey",
        "original_name": "Judy Jeffrey",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 89,
        "character": "Book Signing Audience",
        "credit_id": "63e1a2607739410086a97b03",
        "order": 32
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909147,
        "known_for_department": "Acting",
        "name": "John Nayagam",
        "original_name": "John Nayagam",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 90,
        "character": "Book Signing Audience",
        "credit_id": "63e1a27e77394100984364ba",
        "order": 33
      },
      {
        "adult": false,
        "gender": 1,
        "id": 3344665,
        "known_for_department": "Acting",
        "name": "Greta Nayagam",
        "original_name": "Greta Nayagam",
        "popularity": 0.6,
        "profile_path": "/8kdHLflqiKL9DMgdDAFk379Qdto.jpg",
        "cast_id": 91,
        "character": "Book Signing Audience",
        "credit_id": "63e1a28577394100cd8e50c2",
        "order": 34
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909150,
        "known_for_department": "Acting",
        "name": "Cathy Chan",
        "original_name": "Cathy Chan",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 92,
        "character": "Book Signing Audience",
        "credit_id": "63e1a28ecb802800a1a51ba7",
        "order": 35
      },
      {
        "adult": false,
        "gender": 2,
        "id": 3909151,
        "known_for_department": "Acting",
        "name": "Adam Sai",
        "original_name": "Adam Sai",
        "popularity": 0.6,
        "profile_path": "/qXC0PMApz7cqmnvdC0v9XJUBE9.jpg",
        "cast_id": 93,
        "character": "Book Signing Audience",
        "credit_id": "63e1a297c8a2d4007f472de3",
        "order": 36
      },
      {
        "adult": false,
        "gender": 2,
        "id": 3909155,
        "known_for_department": "Acting",
        "name": "Jamie Sai",
        "original_name": "Jamie Sai",
        "popularity": 0.6,
        "profile_path": "/pMm6kvtFTnx4SFex5YFCIZIw7p4.jpg",
        "cast_id": 94,
        "character": "Book Signing Audience",
        "credit_id": "63e1a360cb802800c007567e",
        "order": 37
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2003778,
        "known_for_department": "Acting",
        "name": "Jakari Fraser",
        "original_name": "Jakari Fraser",
        "popularity": 2.231,
        "profile_path": "/bjlJKjrptiCJ3kt8u8F6tkFDHne.jpg",
        "cast_id": 95,
        "character": "Young Ant-Man Fan",
        "credit_id": "63e1a36dac8e6b00c3f456c4",
        "order": 38
      },
      {
        "adult": false,
        "gender": 1,
        "id": 56358,
        "known_for_department": "Acting",
        "name": "Patricia Belcher",
        "original_name": "Patricia Belcher",
        "popularity": 10.791,
        "profile_path": "/8h5cLajSjv3fLIeAyuYyNxj7gte.jpg",
        "cast_id": 96,
        "character": "Ant-Man Fan",
        "credit_id": "63e1a375773941007cc574ae",
        "order": 39
      },
      {
        "adult": false,
        "gender": 0,
        "id": 937146,
        "known_for_department": "Acting",
        "name": "Mark Oliver Everett",
        "original_name": "Mark Oliver Everett",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 97,
        "character": "Jogger with Dog",
        "credit_id": "63e1a4c67776f000bce64d26",
        "order": 40
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1434041,
        "known_for_department": "Acting",
        "name": "Ruben Rabasa",
        "original_name": "Ruben Rabasa",
        "popularity": 3.687,
        "profile_path": "/terEHwAQdJ2XnzZIWu1C7Jccfkm.jpg",
        "cast_id": 43,
        "character": "Café Owner",
        "credit_id": "63571a85c9dbf9007f038ca3",
        "order": 41
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3408058,
        "known_for_department": "Acting",
        "name": "Melanie Garcia",
        "original_name": "Melanie Garcia",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 98,
        "character": "Barista",
        "credit_id": "63e1a4e2cb8028007fb50d62",
        "order": 42
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1224999,
        "known_for_department": "Acting",
        "name": "Gregg Turkington",
        "original_name": "Gregg Turkington",
        "popularity": 4.895,
        "profile_path": "/bjOZYkDXbVGSw8B6NHamYlDSBPB.jpg",
        "cast_id": 42,
        "character": "Dale",
        "credit_id": "632f8db69ac535007ce2a43b",
        "order": 43
      },
      {
        "adult": false,
        "gender": 1,
        "id": 3232721,
        "known_for_department": "Acting",
        "name": "Sierra Katow",
        "original_name": "Sierra Katow",
        "popularity": 1.052,
        "profile_path": "/s6wPlFzNH59l9rPlmfythPHV0rz.jpg",
        "cast_id": 99,
        "character": "Waiter",
        "credit_id": "63e1a502ac8e6b007b6b2a85",
        "order": 44
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1943331,
        "known_for_department": "Acting",
        "name": "Ryan Bergara",
        "original_name": "Ryan Bergara",
        "popularity": 5.388,
        "profile_path": "/guAHbeoPuRcNUop14jgfHMYKK31.jpg",
        "cast_id": 100,
        "character": "Toasting Man",
        "credit_id": "63e1a50b7776f0008344457e",
        "order": 45
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1702762,
        "known_for_department": "Acting",
        "name": "Marielle Scott",
        "original_name": "Marielle Scott",
        "popularity": 5.836,
        "profile_path": "/ncBS65taswzGDBsY4g4ZFFlmqGJ.jpg",
        "cast_id": 101,
        "character": "Toasting Woman",
        "credit_id": "63e1a51477394100cd8e5420",
        "order": 46
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909166,
        "known_for_department": "Acting",
        "name": "Jake Millgard",
        "original_name": "Jake Millgard",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 102,
        "character": "Jogger",
        "credit_id": "63e1a5267776f000bce64da2",
        "order": 47
      },
      {
        "adult": false,
        "gender": 1,
        "id": 39568,
        "known_for_department": "Acting",
        "name": "Dey Young",
        "original_name": "Dey Young",
        "popularity": 8.152,
        "profile_path": "/wHgYRlGBk5tiwM6r7ZSkdkc8H7f.jpg",
        "cast_id": 103,
        "character": "Woman with Dog",
        "credit_id": "63e1a530cb8028007b6c2247",
        "order": 48
      },
      {
        "adult": false,
        "gender": 1,
        "id": 2999652,
        "known_for_department": "Acting",
        "name": "Briza Covarrubias",
        "original_name": "Briza Covarrubias",
        "popularity": 0.6,
        "profile_path": "/9DNjiEFthUGRAi5s50DVVEzb8Gp.jpg",
        "cast_id": 104,
        "character": "Hostess",
        "credit_id": "63e1a53c7739410086a97edc",
        "order": 49
      },
      {
        "adult": false,
        "gender": 1,
        "id": 2341456,
        "known_for_department": "Acting",
        "name": "Tess Aubert",
        "original_name": "Tess Aubert",
        "popularity": 2.058,
        "profile_path": "/95SHYLlGYSpYfUrPA0HUtmJElgW.jpg",
        "cast_id": 105,
        "character": "Waitstaff",
        "credit_id": "63e1a54ac8a2d4009d0690d1",
        "order": 50
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2449433,
        "known_for_department": "Acting",
        "name": "David J. Castillo",
        "original_name": "David J. Castillo",
        "popularity": 0.6,
        "profile_path": "/1kC9rkIcO5mPxufdVaEJKIVXTJ3.jpg",
        "cast_id": 106,
        "character": "Waitstaff",
        "credit_id": "63e1a559cb8028007fb50dff",
        "order": 51
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909168,
        "known_for_department": "Acting",
        "name": "Sir Cornwell",
        "original_name": "Sir Cornwell",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 107,
        "character": "Waitstaff",
        "credit_id": "63e1a563773941009843688e",
        "order": 52
      },
      {
        "adult": false,
        "gender": 2,
        "id": 149708,
        "known_for_department": "Acting",
        "name": "Alan Heitz",
        "original_name": "Alan Heitz",
        "popularity": 2.358,
        "profile_path": "/3MA5nyQX9ZCPiUjjCJc97pWrLMA.jpg",
        "cast_id": 108,
        "character": "Waitstaff",
        "credit_id": "63e1a56aac8e6b00a0b9e83f",
        "order": 53
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909170,
        "known_for_department": "Acting",
        "name": "Esther McAuley",
        "original_name": "Esther McAuley",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 109,
        "character": "Alien World Citizen",
        "credit_id": "63e1a5847739410086a97f67",
        "order": 54
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909171,
        "known_for_department": "Acting",
        "name": "Aisling Mara Andreica",
        "original_name": "Aisling Mara Andreica",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 110,
        "character": "Alien World Citizen",
        "credit_id": "63e1a5a0ac8e6b008edcf325",
        "order": 55
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1202168,
        "known_for_department": "Acting",
        "name": "Milton Lopes",
        "original_name": "Milton Lopes",
        "popularity": 0.6,
        "profile_path": "/yDiWqNKpa1KeiMWh5BLOdzbqUXs.jpg",
        "cast_id": 111,
        "character": "Alien World Citizen",
        "credit_id": "63e1a5aeac8e6b0084992ee9",
        "order": 56
      },
      {
        "adult": false,
        "gender": 2,
        "id": 75038,
        "known_for_department": "Acting",
        "name": "Roger Craig Smith",
        "original_name": "Roger Craig Smith",
        "popularity": 3.778,
        "profile_path": "/6oE356GbRHAf91Llw7LDpvsAf5L.jpg",
        "cast_id": 112,
        "character": "Quantumnaut Voices (voice)",
        "credit_id": "63e1a5cacb802800a1a52060",
        "order": 57
      },
      {
        "adult": false,
        "gender": 2,
        "id": 71536,
        "known_for_department": "Sound",
        "name": "Matthew Wood",
        "original_name": "Matthew Wood",
        "popularity": 5.557,
        "profile_path": "/u1UjHLTeS5Dregg85A3GICf7Nkf.jpg",
        "cast_id": 113,
        "character": "Quantumnaut Voices (voice)",
        "credit_id": "63e1a5d1cb80280083c68c19",
        "order": 58
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1717900,
        "known_for_department": "Acting",
        "name": "Loveday Smith",
        "original_name": "Loveday Smith",
        "popularity": 0.6,
        "profile_path": "/wCfliAxqrl7vR3MIFApPszHAXag.jpg",
        "cast_id": 114,
        "character": "Janet Van Dyne Acting Double",
        "credit_id": "63e1a5dacb8028007b6c234d",
        "order": 59
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909172,
        "known_for_department": "Acting",
        "name": "John Townsend",
        "original_name": "John Townsend",
        "popularity": 0.6,
        "profile_path": null,
        "cast_id": 115,
        "character": "Lord Krylar Acting Photo Double",
        "credit_id": "63e1a5f47776f0008c45be6a",
        "order": 60
      },
      {
        "adult": false,
        "gender": 2,
        "id": 91606,
        "known_for_department": "Acting",
        "name": "Tom Hiddleston",
        "original_name": "Tom Hiddleston",
        "popularity": 21.311,
        "profile_path": "/mclHxMm8aPlCPKptP67257F5GPo.jpg",
        "cast_id": 184,
        "character": "Loki (uncredited)",
        "credit_id": "63ed4ae68e870200dc7d0048",
        "order": 61
      },
      {
        "adult": false,
        "gender": 2,
        "id": 887,
        "known_for_department": "Acting",
        "name": "Owen Wilson",
        "original_name": "Owen Wilson",
        "popularity": 62.592,
        "profile_path": "/ptiUjN2YcXbvCr6xawMFX9lYezk.jpg",
        "cast_id": 188,
        "character": "Mobius M. Mobius (uncredited)",
        "credit_id": "63ee834b1c6aa700d5c1c4a6",
        "order": 62
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1360010,
        "known_for_department": "Acting",
        "name": "Abby Ryder Fortson",
        "original_name": "Abby Ryder Fortson",
        "popularity": 17.43,
        "profile_path": "/DPIxORe7Sco6xVIKVbIsHlRYCI.jpg",
        "cast_id": 215,
        "character": "Cassie Lang (archive footage) (uncredited)",
        "credit_id": "63f2a7b94a4bfc00f07da114",
        "order": 63
      }
    ],
    "crew": [
      {
        "adult": false,
        "gender": 1,
        "id": 7232,
        "known_for_department": "Production",
        "name": "Sarah Halley Finn",
        "original_name": "Sarah Halley Finn",
        "popularity": 9.492,
        "profile_path": "/jxECVz09YGZAg1AmdzfEkPm4xeY.jpg",
        "credit_id": "6383fc955e14e500862fd070",
        "department": "Production",
        "job": "Casting"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 7624,
        "known_for_department": "Writing",
        "name": "Stan Lee",
        "original_name": "Stan Lee",
        "popularity": 15.209,
        "profile_path": "/kKeyWoFtTqOPsbmwylNHmuB3En9.jpg",
        "credit_id": "5da88fdbe6d3cc0018b04e35",
        "department": "Writing",
        "job": "Characters"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 10850,
        "known_for_department": "Production",
        "name": "Kevin Feige",
        "original_name": "Kevin Feige",
        "popularity": 12.966,
        "profile_path": "/kCBqXZ5PT5udYGEj2wfTSFbLMvT.jpg",
        "credit_id": "5da88fc8c3c891001316419b",
        "department": "Production",
        "job": "Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 9341,
        "known_for_department": "Camera",
        "name": "Bill Pope",
        "original_name": "Bill Pope",
        "popularity": 2.52,
        "profile_path": "/kpakvuSrk1D9D8WMt5SOi4Rs2EV.jpg",
        "credit_id": "6289717ae004a66f32b15131",
        "department": "Camera",
        "job": "Director of Photography"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 8410,
        "known_for_department": "Art",
        "name": "Richard Roberts",
        "original_name": "Richard Roberts",
        "popularity": 0.652,
        "profile_path": null,
        "credit_id": "63e1aa33528b2e0099360539",
        "department": "Art",
        "job": "Set Decoration"
      },
      {
        "adult": false,
        "gender": 1,
        "id": 11271,
        "known_for_department": "Costume & Make-Up",
        "name": "Sammy Sheldon",
        "original_name": "Sammy Sheldon",
        "popularity": 1.307,
        "profile_path": null,
        "credit_id": "617e178da097dc002aaffb96",
        "department": "Costume & Make-Up",
        "job": "Costume Design"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 59026,
        "known_for_department": "Directing",
        "name": "Peyton Reed",
        "original_name": "Peyton Reed",
        "popularity": 11.251,
        "profile_path": "/aucXNycAtFREMIKr6ikmHvd2Mmp.jpg",
        "credit_id": "5dbc9866d388ae0016d85970",
        "department": "Directing",
        "job": "Director"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 18866,
        "known_for_department": "Writing",
        "name": "Jack Kirby",
        "original_name": "Jack Kirby",
        "popularity": 4.131,
        "profile_path": "/ihhR019gL1WrXdSQNJITAY6dont.jpg",
        "credit_id": "5dbd321c9638640016e10f30",
        "department": "Writing",
        "job": "Characters"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 18876,
        "known_for_department": "Writing",
        "name": "Larry Lieber",
        "original_name": "Larry Lieber",
        "popularity": 2.648,
        "profile_path": "/6zFjMrk50yZri9KiVqli477gWYB.jpg",
        "credit_id": "63e1a8d57739410086a98434",
        "department": "Writing",
        "job": "Characters"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 23486,
        "known_for_department": "Sound",
        "name": "Christophe Beck",
        "original_name": "Christophe Beck",
        "popularity": 2.415,
        "profile_path": "/n3U0OPETTZGTx4mgsrryARKphR4.jpg",
        "credit_id": "62ca36d1d705940051fd2ff4",
        "department": "Sound",
        "job": "Original Music Composer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 24192,
        "known_for_department": "Sound",
        "name": "Dave Jordan",
        "original_name": "Dave Jordan",
        "popularity": 2.163,
        "profile_path": null,
        "credit_id": "6383fca0fb83460099604950",
        "department": "Sound",
        "job": "Music Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 29611,
        "known_for_department": "Visual Effects",
        "name": "Paul Corbould",
        "original_name": "Paul Corbould",
        "popularity": 1.566,
        "profile_path": null,
        "credit_id": "63e14b006f6a990093dd1bee",
        "department": "Visual Effects",
        "job": "Special Effects Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 36657,
        "known_for_department": "Art",
        "name": "Nick Gottschalk",
        "original_name": "Nick Gottschalk",
        "popularity": 1.353,
        "profile_path": null,
        "credit_id": "63e14dc5a313b800966fed8e",
        "department": "Art",
        "job": "Supervising Art Director"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 15783,
        "known_for_department": "Writing",
        "name": "Harlan Ellison",
        "original_name": "Harlan Ellison",
        "popularity": 1.135,
        "profile_path": "/7Y3x4iBiI0a10o7Jzc9lwC4cjX9.jpg",
        "credit_id": "63e1b2e2528b2e0099360f44",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 57027,
        "known_for_department": "Production",
        "name": "Louis D'Esposito",
        "original_name": "Louis D'Esposito",
        "popularity": 6.849,
        "profile_path": "/mPy6hxHrHoEOWdljLyZM6DNBSPn.jpg",
        "credit_id": "6032c87f7f6c8d003d1257a6",
        "department": "Production",
        "job": "Executive Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 59667,
        "known_for_department": "Camera",
        "name": "Steve Yedlin",
        "original_name": "Steve Yedlin",
        "popularity": 2.547,
        "profile_path": "/u5TFf0Lpe4PZbMFEGWKBKjGFp6G.jpg",
        "credit_id": "6431fd709a64350666c7474f",
        "department": "Camera",
        "job": "Additional Photography"
      },
      {
        "adult": false,
        "gender": 1,
        "id": 113674,
        "known_for_department": "Production",
        "name": "Victoria Alonso",
        "original_name": "Victoria Alonso",
        "popularity": 4.97,
        "profile_path": "/7HfCAsks2D1xMsW4HHhFUuvptmq.jpg",
        "credit_id": "6032c88b96e30b003f258ecf",
        "department": "Production",
        "job": "Executive Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 75804,
        "known_for_department": "Production",
        "name": "Kevin De La Noy",
        "original_name": "Kevin De La Noy",
        "popularity": 2.267,
        "profile_path": null,
        "credit_id": "637d51c975f1ad00886e866b",
        "department": "Production",
        "job": "Executive Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 75804,
        "known_for_department": "Production",
        "name": "Kevin De La Noy",
        "original_name": "Kevin De La Noy",
        "popularity": 2.267,
        "profile_path": null,
        "credit_id": "63f074b715376c0095b11a4d",
        "department": "Production",
        "job": "Unit Production Manager"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 114017,
        "known_for_department": "Production",
        "name": "Karl McMillan",
        "original_name": "Karl McMillan",
        "popularity": 1.195,
        "profile_path": null,
        "credit_id": "63f2aee115376c00cb2388a8",
        "department": "Production",
        "job": "Production Supervisor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 141359,
        "known_for_department": "Writing",
        "name": "Roy Thomas",
        "original_name": "Roy Thomas",
        "popularity": 3.552,
        "profile_path": null,
        "credit_id": "63e1b5a3ac8e6b00c3f46ce1",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 985161,
        "known_for_department": "Acting",
        "name": "Mark Waid",
        "original_name": "Mark Waid",
        "popularity": 3.097,
        "profile_path": null,
        "credit_id": "63e1b5abcb8028007b6c3608",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1117747,
        "known_for_department": "Production",
        "name": "Mitchell Bell",
        "original_name": "Mitchell Bell",
        "popularity": 1.806,
        "profile_path": "/vTgWJRc3ABqePIrOwsmr87aLik6.jpg",
        "credit_id": "6383fcce1b157d0097167ec4",
        "department": "Production",
        "job": "Co-Producer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1117748,
        "known_for_department": "Production",
        "name": "Stephen Broussard",
        "original_name": "Stephen Broussard",
        "popularity": 3.771,
        "profile_path": null,
        "credit_id": "637d51bd75f1ad00fcf391ea",
        "department": "Production",
        "job": "Producer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1145873,
        "known_for_department": "Acting",
        "name": "John Buscema",
        "original_name": "John Buscema",
        "popularity": 3.224,
        "profile_path": null,
        "credit_id": "63e1b29477394100e9101760",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1191111,
        "known_for_department": "Sound",
        "name": "Justin Doyle",
        "original_name": "Justin Doyle",
        "popularity": 1.052,
        "profile_path": null,
        "credit_id": "63ed4106699fb70084e1e1a5",
        "department": "Sound",
        "job": "Sound Effects Editor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1194953,
        "known_for_department": "Crew",
        "name": "John Byrne",
        "original_name": "John Byrne",
        "popularity": 2.735,
        "profile_path": null,
        "credit_id": "63e1b2a7528b2e0099360f04",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1195200,
        "known_for_department": "Writing",
        "name": "David Michelinie",
        "original_name": "David Michelinie",
        "popularity": 1.301,
        "profile_path": null,
        "credit_id": "63e1b478ac8e6b00c3f46be0",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1213170,
        "known_for_department": "Writing",
        "name": "Allan Heinberg",
        "original_name": "Allan Heinberg",
        "popularity": 4.011,
        "profile_path": "/mfwsR12OwlpxrJoEcQiBLJmGG8S.jpg",
        "credit_id": "63e1b558cb80280093e6a400",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1222494,
        "known_for_department": "Acting",
        "name": "Walt Simonson",
        "original_name": "Walt Simonson",
        "popularity": 1.856,
        "profile_path": "/5dD0gNaTQBmFUErEr4Wj7DpBbia.jpg",
        "credit_id": "63e1b599ac8e6b007b6b3fdb",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1225024,
        "known_for_department": "Writing",
        "name": "Jeff Loveness",
        "original_name": "Jeff Loveness",
        "popularity": 4.357,
        "profile_path": "/uq3MZhGWq6jvDgrYiHkofUpd5e4.jpg",
        "credit_id": "6383fdf4b3316b007f3c2363",
        "department": "Writing",
        "job": "Writer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1238004,
        "known_for_department": "Acting",
        "name": "Sal Buscema",
        "original_name": "Sal Buscema",
        "popularity": 1.419,
        "profile_path": null,
        "credit_id": "63e1b4fecb802800c0076c7c",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1319752,
        "known_for_department": "Costume & Make-Up",
        "name": "Nicole Young",
        "original_name": "Nicole Young",
        "popularity": 0.656,
        "profile_path": null,
        "credit_id": "63ed40f3813cb600dc0798c9",
        "department": "Costume & Make-Up",
        "job": "Costume Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1335209,
        "known_for_department": "Editing",
        "name": "Adam Gerstel",
        "original_name": "Adam Gerstel",
        "popularity": 1.22,
        "profile_path": null,
        "credit_id": "6383fdce2e06970292e3d349",
        "department": "Editing",
        "job": "Editor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1372782,
        "known_for_department": "Writing",
        "name": "Steve Englehart",
        "original_name": "Steve Englehart",
        "popularity": 2.241,
        "profile_path": null,
        "credit_id": "63e1b5387776f0009a7dd7e7",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1373701,
        "known_for_department": "Art",
        "name": "Jordana Finkel",
        "original_name": "Jordana Finkel",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63ed41771f3e60007fb635aa",
        "department": "Art",
        "job": "Art Direction"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1382000,
        "known_for_department": "Writing",
        "name": "Brian Michael Bendis",
        "original_name": "Brian Michael Bendis",
        "popularity": 1.329,
        "profile_path": "/zYcyWooAjXFJCU7GVyzvHDqpPP0.jpg",
        "credit_id": "63e1b4f6c8a2d400d40007c4",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1388898,
        "known_for_department": "Camera",
        "name": "Sam Renton",
        "original_name": "Sam Renton",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63f076b1a67254007de84644",
        "department": "Camera",
        "job": "Second Unit Director of Photography"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1394001,
        "known_for_department": "Art",
        "name": "Katrina Mackay",
        "original_name": "Katrina Mackay",
        "popularity": 0.622,
        "profile_path": null,
        "credit_id": "63ed41d91b729400866dab98",
        "department": "Art",
        "job": "Art Direction"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1398085,
        "known_for_department": "Art",
        "name": "David Balfour",
        "original_name": "David Balfour",
        "popularity": 1.121,
        "profile_path": null,
        "credit_id": "63f07596a24c5000c0b8a0d2",
        "department": "Art",
        "job": "Property Master"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1398107,
        "known_for_department": "Crew",
        "name": "Gary Powell",
        "original_name": "Gary Powell",
        "popularity": 1.3,
        "profile_path": "/eUxi90MIr0coNyRK516dzEzElfA.jpg",
        "credit_id": "63f074f34a4bfc008641a25a",
        "department": "Crew",
        "job": "Stunt Coordinator"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1403989,
        "known_for_department": "Writing",
        "name": "Tom Palmer",
        "original_name": "Tom Palmer",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63e1b4c377394100e9101988",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1404875,
        "known_for_department": "Directing",
        "name": "Jo Beckett",
        "original_name": "Jo Beckett",
        "popularity": 0.732,
        "profile_path": null,
        "credit_id": "6032c86c1d3143003c0b09a7",
        "department": "Directing",
        "job": "Script Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1409703,
        "known_for_department": "Writing",
        "name": "Geof Isherwood",
        "original_name": "Geof Isherwood",
        "popularity": 1.565,
        "profile_path": null,
        "credit_id": "63e1b562cb8028007fb52122",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1419264,
        "known_for_department": "Visual Effects",
        "name": "Fiona Campbell Westgate",
        "original_name": "Fiona Campbell Westgate",
        "popularity": 1.214,
        "profile_path": null,
        "credit_id": "63e14af3fd6fa1007a23ae3a",
        "department": "Visual Effects",
        "job": "Visual Effects Producer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1419604,
        "known_for_department": "Visual Effects",
        "name": "Justin Cornish",
        "original_name": "Justin Cornish",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63f07835a24c5000c0b8a1f0",
        "department": "Visual Effects",
        "job": "Visual Effects Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1419605,
        "known_for_department": "Visual Effects",
        "name": "Brooke Lyndon-Stanford",
        "original_name": "Brooke Lyndon-Stanford",
        "popularity": 1.558,
        "profile_path": null,
        "credit_id": "6445b692b3f6f5049c9f1d50",
        "department": "Visual Effects",
        "job": "VFX Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1420188,
        "known_for_department": "Visual Effects",
        "name": "Malte Sarnes",
        "original_name": "Malte Sarnes",
        "popularity": 0.84,
        "profile_path": null,
        "credit_id": "63f077eea24c5000d4e3218e",
        "department": "Visual Effects",
        "job": "Visual Effects Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1421642,
        "known_for_department": "Costume & Make-Up",
        "name": "Jan Sewell",
        "original_name": "Jan Sewell",
        "popularity": 1.338,
        "profile_path": null,
        "credit_id": "63e14d51fd6fa100bb110326",
        "department": "Costume & Make-Up",
        "job": "Hair Designer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1421642,
        "known_for_department": "Costume & Make-Up",
        "name": "Jan Sewell",
        "original_name": "Jan Sewell",
        "popularity": 1.338,
        "profile_path": null,
        "credit_id": "63e14d56629b2c007f850c3b",
        "department": "Costume & Make-Up",
        "job": "Makeup Designer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1428905,
        "known_for_department": "Crew",
        "name": "Laura Jennings",
        "original_name": "Laura Jennings",
        "popularity": 0.856,
        "profile_path": null,
        "credit_id": "6383fdda229ae21597d38ed1",
        "department": "Editing",
        "job": "Editor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1456373,
        "known_for_department": "Visual Effects",
        "name": "Wesley Sewell",
        "original_name": "Wesley Sewell",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63f077f7a6725400c9f284a2",
        "department": "Visual Effects",
        "job": "Visual Effects Supervisor"
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1467989,
        "known_for_department": "Crew",
        "name": "Kelli Barksdale",
        "original_name": "Kelli Barksdale",
        "popularity": 2.226,
        "profile_path": "/Aa45gS9B6DMR8ab4fdBan12qFLu.jpg",
        "credit_id": "64713de0be2d490116c86b41",
        "department": "Crew",
        "job": "Stunts"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1469986,
        "known_for_department": "Acting",
        "name": "Thomas E. Sullivan",
        "original_name": "Thomas E. Sullivan",
        "popularity": 3.856,
        "profile_path": "/AqiLyqvExUDtzRqmirMcgY4D6Rt.jpg",
        "credit_id": "63f2a7744a4bfc00f07da0fa",
        "department": "Crew",
        "job": "Acting Double"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1537723,
        "known_for_department": "Production",
        "name": "Miranda Marks",
        "original_name": "Miranda Marks",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63f2aed733a5330085d8123b",
        "department": "Production",
        "job": "Production Supervisor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1538385,
        "known_for_department": "Visual Effects",
        "name": "Lawson Deming",
        "original_name": "Lawson Deming",
        "popularity": 1.28,
        "profile_path": "/yCvyACWcjXzJYILMyX5UroOD2Nm.jpg",
        "credit_id": "63f0785ba67254007de846ee",
        "department": "Visual Effects",
        "job": "Visual Effects Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1550780,
        "known_for_department": "Sound",
        "name": "Jonathan Borland",
        "original_name": "Jonathan Borland",
        "popularity": 0.794,
        "profile_path": null,
        "credit_id": "63ed6d461f3e600079e04039",
        "department": "Sound",
        "job": "Sound Effects Editor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1551810,
        "known_for_department": "Art",
        "name": "Liam Georgensen",
        "original_name": "Liam Georgensen",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63ed41851f3e6000c03304cd",
        "department": "Art",
        "job": "Art Direction"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1551811,
        "known_for_department": "Art",
        "name": "Hugh McClelland",
        "original_name": "Hugh McClelland",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63ed41ecf925320079c9a861",
        "department": "Art",
        "job": "Art Direction"
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1581215,
        "known_for_department": "Acting",
        "name": "Lisa Kaminir",
        "original_name": "Lisa Kaminir",
        "popularity": 0.825,
        "profile_path": "/Advotdglh88vPfHiupk8Rk5otJ7.jpg",
        "credit_id": "63f2a755a24c5000c0b98641",
        "department": "Crew",
        "job": "Acting Double"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1590413,
        "known_for_department": "Visual Effects",
        "name": "Dan DeLeeuw",
        "original_name": "Dan DeLeeuw",
        "popularity": 1.391,
        "profile_path": null,
        "credit_id": "63f07497caaca200892dcf2d",
        "department": "Directing",
        "job": "Second Unit Director"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1608224,
        "known_for_department": "Sound",
        "name": "Jessey Drake",
        "original_name": "Jessey Drake",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63ed41182f266b00896aa674",
        "department": "Sound",
        "job": "Foley Supervisor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1634469,
        "known_for_department": "Sound",
        "name": "Tim Davies",
        "original_name": "Tim Davies",
        "popularity": 1.22,
        "profile_path": null,
        "credit_id": "63e14eada313b80084ddc609",
        "department": "Sound",
        "job": "Conductor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1638257,
        "known_for_department": "Costume & Make-Up",
        "name": "Conor O'Sullivan",
        "original_name": "Conor O'Sullivan",
        "popularity": 0.798,
        "profile_path": null,
        "credit_id": "63e1a9b97739410098436e53",
        "department": "Visual Effects",
        "job": "Creature Design"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1669139,
        "known_for_department": "Sound",
        "name": "Samson Neslund",
        "original_name": "Samson Neslund",
        "popularity": 0.706,
        "profile_path": null,
        "credit_id": "63ed6d3d1f3e6000a1c5e135",
        "department": "Sound",
        "job": "Sound Effects Editor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1744229,
        "known_for_department": "Art",
        "name": "Irene Dimarca",
        "original_name": "Irene Dimarca",
        "popularity": 0.608,
        "profile_path": null,
        "credit_id": "63ed421a813cb60096aaf810",
        "department": "Art",
        "job": "Assistant Art Director"
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1756237,
        "known_for_department": "Sound",
        "name": "Kimberly Patrick",
        "original_name": "Kimberly Patrick",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63ed4150f9253200c30032bc",
        "department": "Sound",
        "job": "Sound Designer"
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1756237,
        "known_for_department": "Sound",
        "name": "Kimberly Patrick",
        "original_name": "Kimberly Patrick",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63ed41488e870200dc7cfdd5",
        "department": "Sound",
        "job": "Supervising Sound Editor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1797241,
        "known_for_department": "Visual Effects",
        "name": "Axel Bonami",
        "original_name": "Axel Bonami",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63f077e6a24c500078c86d94",
        "department": "Visual Effects",
        "job": "Visual Effects Supervisor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1804321,
        "known_for_department": "Crew",
        "name": "Roger Stern",
        "original_name": "Roger Stern",
        "popularity": 2.87,
        "profile_path": null,
        "credit_id": "63e1b4e57776f0009a7dd78e",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1829852,
        "known_for_department": "Camera",
        "name": "Steve Ellingworth",
        "original_name": "Steve Ellingworth",
        "popularity": 2.231,
        "profile_path": null,
        "credit_id": "63f075a7caaca200a19ac912",
        "department": "Camera",
        "job": "Key Grip"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1888010,
        "known_for_department": "Crew",
        "name": "Tom DeFalco",
        "original_name": "Tom DeFalco",
        "popularity": 0.662,
        "profile_path": "/6GCTvuP3D0utUA8jk5k99s0MySK.jpg",
        "credit_id": "63e1b2ce77394100984378c1",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1888011,
        "known_for_department": "Crew",
        "name": "Ron Frenz",
        "original_name": "Ron Frenz",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63e1b540cb802800a1a53350",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1935207,
        "known_for_department": "Visual Effects",
        "name": "Ryan Meinerding",
        "original_name": "Ryan Meinerding",
        "popularity": 1.004,
        "profile_path": null,
        "credit_id": "6383fcb3bf09d100afd15bde",
        "department": "Visual Effects",
        "job": "Visual Development"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 1998249,
        "known_for_department": "Visual Effects",
        "name": "Jesse James Chisholm",
        "original_name": "Jesse James Chisholm",
        "popularity": 0.764,
        "profile_path": null,
        "credit_id": "6383fdaeb3316b007f3c230d",
        "department": "Visual Effects",
        "job": "Visual Effects Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2017215,
        "known_for_department": "Art",
        "name": "Keely Lanigan-Atkins",
        "original_name": "Keely Lanigan-Atkins",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63ed423f699fb7009e3daa7d",
        "department": "Art",
        "job": "Assistant Art Director"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2026509,
        "known_for_department": "Crew",
        "name": "Brian Kruse",
        "original_name": "Brian Kruse",
        "popularity": 0.85,
        "profile_path": null,
        "credit_id": "63f2a76533a5330085d81098",
        "department": "Crew",
        "job": "Acting Double"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2082779,
        "known_for_department": "Sound",
        "name": "Michael Paraskevas",
        "original_name": "Michael Paraskevas",
        "popularity": 1.091,
        "profile_path": "/x8vxUS4SqV6NOlvHmhgtaw7CZKz.jpg",
        "credit_id": "63f2af1ba24c5000a13d2ab7",
        "department": "Sound",
        "job": "Additional Soundtrack"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2090901,
        "known_for_department": "Art",
        "name": "Aleksi Briclot",
        "original_name": "Aleksi Briclot",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "6032c8da7f6c8d003c1212bf",
        "department": "Art",
        "job": "Concept Artist"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2137087,
        "known_for_department": "Crew",
        "name": "Dave Cockrum",
        "original_name": "Dave Cockrum",
        "popularity": 1.435,
        "profile_path": "/mrglhlJzipPgh71tM0QWiCdWAm9.jpg",
        "credit_id": "63e1b2c6ac8e6b0084993f53",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2153753,
        "known_for_department": "Visual Effects",
        "name": "Jason Greenblum",
        "original_name": "Jason Greenblum",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63f077dd4a4bfc008ecdd3f1",
        "department": "Visual Effects",
        "job": "Visual Effects Supervisor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2296692,
        "known_for_department": "Writing",
        "name": "Steve Epting",
        "original_name": "Steve Epting",
        "popularity": 0.968,
        "profile_path": null,
        "credit_id": "63e1b2ec77394100e91017a5",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2303244,
        "known_for_department": "Acting",
        "name": "Kevin Changaris",
        "original_name": "Kevin Changaris",
        "popularity": 1.774,
        "profile_path": "/xH2SVCc3XaqMSvJxrovSiLP67H9.jpg",
        "credit_id": "63f2a74133a5330085d8108b",
        "department": "Crew",
        "job": "Acting Double"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2387223,
        "known_for_department": "Sound",
        "name": "Paola Magrans",
        "original_name": "Paola Magrans",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63ed6d2a1f3e6000c0331241",
        "department": "Sound",
        "job": "Foley Editor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2391793,
        "known_for_department": "Crew",
        "name": "Cristian Camaroschi",
        "original_name": "Cristian Camaroschi",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63f0784ca67254008202a70a",
        "department": "Visual Effects",
        "job": "Visual Effects Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2414066,
        "known_for_department": "Writing",
        "name": "Bob Layton",
        "original_name": "Bob Layton",
        "popularity": 0.732,
        "profile_path": null,
        "credit_id": "63e1b46bcb8028007fb5202b",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2479720,
        "known_for_department": "Crew",
        "name": "Jordan Ballard",
        "original_name": "Jordan Ballard",
        "popularity": 0.968,
        "profile_path": null,
        "credit_id": "63f0751e4a4bfc0096379f40",
        "department": "Crew",
        "job": "Post Production Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2657888,
        "known_for_department": "Crew",
        "name": "David Hodgins",
        "original_name": "David Hodgins",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63f0774415376c008335a2e4",
        "department": "Visual Effects",
        "job": "Visual Effects Supervisor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2699115,
        "known_for_department": "Sound",
        "name": "Goeun Lee Everett",
        "original_name": "Goeun Lee Everett",
        "popularity": 0.665,
        "profile_path": null,
        "credit_id": "63ed412b2f266b00a1decdd5",
        "department": "Sound",
        "job": "Sound Effects Editor"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2727055,
        "known_for_department": "Crew",
        "name": "Olivier Coipel",
        "original_name": "Olivier Coipel",
        "popularity": 1.15,
        "profile_path": null,
        "credit_id": "63e1b5187776f0007bb2d9e2",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2743313,
        "known_for_department": "Acting",
        "name": "Antoine Jackson",
        "original_name": "Antoine Jackson",
        "popularity": 1.089,
        "profile_path": null,
        "credit_id": "63f2a74b15376c0083369364",
        "department": "Crew",
        "job": "Acting Double"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2772764,
        "known_for_department": "Costume & Make-Up",
        "name": "Louise Young",
        "original_name": "Louise Young",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63ed40a58e870200dc7cfdaa",
        "department": "Costume & Make-Up",
        "job": "Makeup Artist"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2808013,
        "known_for_department": "Visual Effects",
        "name": "Reetu Aggarwal",
        "original_name": "Reetu Aggarwal",
        "popularity": 2.106,
        "profile_path": null,
        "credit_id": "63a5f4e08e8d3000a1d0b2e4",
        "department": "Visual Effects",
        "job": "3D Artist"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2812881,
        "known_for_department": "Art",
        "name": "Jasmine Lean",
        "original_name": "Jasmine Lean",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63ed424a699fb700cee1c2ac",
        "department": "Art",
        "job": "Assistant Art Director"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2817061,
        "known_for_department": "Writing",
        "name": "Herb Trimpe",
        "original_name": "Herb Trimpe",
        "popularity": 0.656,
        "profile_path": null,
        "credit_id": "63e1b4eeac8e6b00a0b9fa58",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2919240,
        "known_for_department": "Sound",
        "name": "Gottfried Rabl",
        "original_name": "Gottfried Rabl",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63e14ebe4da3d4009dd9315e",
        "department": "Sound",
        "job": "Conductor"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2969671,
        "known_for_department": "Crew",
        "name": "Archie Goodwin",
        "original_name": "Archie Goodwin",
        "popularity": 0.84,
        "profile_path": "/4EW7vvA5UHzEI6Z4uhJYtEXDpQ7.jpg",
        "credit_id": "63e1b54a528b2e0099361159",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2981925,
        "known_for_department": "Art",
        "name": "Will Htay",
        "original_name": "Will Htay",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "6032c89b1d3143003e0af985",
        "department": "Art",
        "job": "Production Design"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2983586,
        "known_for_department": "Crew",
        "name": "Jim Cheung",
        "original_name": "Jim Cheung",
        "popularity": 0.63,
        "profile_path": null,
        "credit_id": "63e1b50fac8e6b007b6b3f47",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 2985688,
        "known_for_department": "Art",
        "name": "Thomas du Crest",
        "original_name": "Thomas du Crest",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "6032c8e76e3deb003e0b4702",
        "department": "Art",
        "job": "Concept Artist"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 3016142,
        "known_for_department": "Crew",
        "name": "Mark Gruenwald",
        "original_name": "Mark Gruenwald",
        "popularity": 1.284,
        "profile_path": null,
        "credit_id": "63e1b306c8a2d4007f4741c8",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3119308,
        "known_for_department": "Sound",
        "name": "Raven Davenport",
        "original_name": "Raven Davenport",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63f078b6caaca20085773b05",
        "department": "Sound",
        "job": "Music Coordinator"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 3202369,
        "known_for_department": "Crew",
        "name": "Jonathan Hickman",
        "original_name": "Jonathan Hickman",
        "popularity": 0.84,
        "profile_path": null,
        "credit_id": "63e1b30f77394100aa293457",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 3429762,
        "known_for_department": "Acting",
        "name": "Ivo Coveney",
        "original_name": "Ivo Coveney",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63e14d176f6a9900790d3076",
        "department": "Costume & Make-Up",
        "job": "Other"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 3539218,
        "known_for_department": "Crew",
        "name": "Terry Dodson",
        "original_name": "Terry Dodson",
        "popularity": 0.652,
        "profile_path": null,
        "credit_id": "63e1b529c8a2d4007c360f72",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 3720135,
        "known_for_department": "Crew",
        "name": "Ernie Hart",
        "original_name": "Ernie Hart",
        "popularity": 1.052,
        "profile_path": null,
        "credit_id": "63e1a8edac8e6b00a0b9ed85",
        "department": "Writing",
        "job": "Characters"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3805368,
        "known_for_department": "Production",
        "name": "Laura Stoltz",
        "original_name": "Laura Stoltz",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "6383fcf01b157d008244c2b5",
        "department": "Production",
        "job": "Co-Producer"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909244,
        "known_for_department": "Crew",
        "name": "David Jones",
        "original_name": "David Jones",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63e1b218ac8e6b007b6b3c2a",
        "department": "Crew",
        "job": "In Memory Of"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909246,
        "known_for_department": "Crew",
        "name": "Larry Alexander",
        "original_name": "Larry Alexander",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63e1b287528b2e00ce8e1d92",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909250,
        "known_for_department": "Crew",
        "name": "Javier Garrón",
        "original_name": "Javier Garrón",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63e1b2fc7776f000dbbefa69",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909271,
        "known_for_department": "Crew",
        "name": "Scott Reed",
        "original_name": "Scott Reed",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63e1b4dbc8a2d400d40007ae",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909273,
        "known_for_department": "Crew",
        "name": "Mike Mayhew",
        "original_name": "Mike Mayhew",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63e1b576ac8e6b00f3815a4c",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909274,
        "known_for_department": "Crew",
        "name": "Miguel Munera",
        "original_name": "Miguel Munera",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63e1b583cb8028007b6c35d3",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3909275,
        "known_for_department": "Crew",
        "name": "Brandon Peterson",
        "original_name": "Brandon Peterson",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63e1b590cb80280083c69e61",
        "department": "Crew",
        "job": "Thanks"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3922201,
        "known_for_department": "Art",
        "name": "Sarah Paddison",
        "original_name": "Sarah Paddison",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63ed42651f3e600079e03402",
        "department": "Art",
        "job": "Standby Art Director"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3927087,
        "known_for_department": "Art",
        "name": "Colin Woodbridge",
        "original_name": "Colin Woodbridge",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63f0766915376c00b1ede5a4",
        "department": "Art",
        "job": "Construction Manager"
      },
      {
        "adult": false,
        "gender": 0,
        "id": 3927099,
        "known_for_department": "Writing",
        "name": "Andrew Reiber",
        "original_name": "Andrew Reiber",
        "popularity": 0.6,
        "profile_path": null,
        "credit_id": "63f076e3a24c5000d4e3212f",
        "department": "Writing",
        "job": "Story Manager"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 4202617,
        "known_for_department": "Crew",
        "name": "Brian Jackson",
        "original_name": "Brian Jackson",
        "popularity": 1.4,
        "profile_path": "/3uForJAYuHFlFPxK7MMtt8RAz0c.jpg",
        "credit_id": "64d11df74d679100e24160ab",
        "department": "Crew",
        "job": "Systems Administrators & Support"
      }
    ]
  }
};

class DetailPage extends StatefulWidget {
  const DetailPage({super.key});

  @override
  State<DetailPage> createState() => _DetailPageState();
}

class _DetailPageState extends State<DetailPage> {
  final _scrollController = ScrollController();

  var _titleOpacity = 0.0;
  final _displayHours = false;

  void _scrollListener() {
    setState(() {
      if (_scrollController.offset > 250) {
        _titleOpacity = min(1, (_scrollController.offset - 250) / 100);
      } else {
        _titleOpacity = 0.0;
      }
    });
  }

  @override
  void initState() {
    _scrollController.addListener(_scrollListener);

    super.initState();
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  Widget buildCredits(BuildContext context, List people) {
    return SizedBox(
      height: 280,
      child: ListView.builder(
        padding: const EdgeInsets.only(top: 5, right: 0, left: 5),
        scrollDirection: Axis.horizontal,
        itemCount: (details["credits"] as Map)["cast"].length,
        itemBuilder: (BuildContext context, int index) {
          var id = people[index]["id"];
          var imagePath = people[index]["profile_path"];
          var title = people[index]["name"] as String;

          String subtitle;

          if (people[index]["character"] != null) {
            subtitle = people[index]["character"] as String;
          } else if (people[index]["job"] != null) {
            subtitle = people[index]["job"] as String;
          } else {
            subtitle = "";
          }

          return PosterTile(
            key: ValueKey(id),
            imagePath: imagePath,
            title: title,
            subtitle: subtitle,
            onTap: () {
              // Navigate to PersonPage
              Navigator.of(context).push(MaterialPageRoute(
                builder: (context) => const PersonPage(),
              ));
            },
          );
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    // convert running time to hours and minutes
    var runtime = (details["runtime"] as int);
    var hours = runtime ~/ 60;
    var minutes =
        runtime % 60 < 10 ? "0${runtime % 60}" : (runtime % 60).toString();

    Widget flexibleSpace = Stack(
      children: [
        Opacity(
          opacity: 1 - _titleOpacity,
          child: FlexibleSpaceBar(
            background: Stack(
              fit: StackFit.expand,
              children: [
                Poster(
                  imagePath: details["backdrop_path"] as String,
                  height: 350,
                  width: double.infinity,
                ),
                DecoratedBox(
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment.bottomCenter,
                      end: Alignment.topCenter,
                      colors: [
                        Colors.black.withOpacity(0.8),
                        Colors.black.withOpacity(0.5)
                      ],
                    ),
                  ),
                ),
                Column(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    Container(
                      decoration: BoxDecoration(
                        boxShadow: [
                          BoxShadow(
                            color: Colors.black.withOpacity(0.5),
                            spreadRadius: 10,
                            blurRadius: 7,
                            offset: const Offset(0, 3),
                          ),
                        ],
                      ),
                      child: Poster(
                        imagePath: details["poster_path"] as String,
                        height: 180,
                        width: 120,
                      ),
                    ),
                    const SizedBox(height: 10),
                    Text(
                      details["title"] as String,
                      style: Theme.of(context).textTheme.headlineMedium,
                      textAlign: TextAlign.center,
                    ),
                    Padding(
                      padding: const EdgeInsets.all(10),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                        children: [
                          Row(children: [
                            const Icon(Icons.calendar_month, size: 10),
                            const SizedBox(width: 2),
                            Text(
                              DateTime.parse(details["release_date"] as String)
                                  .year
                                  .toString(),
                            ),
                          ]),
                          Row(
                            children: [
                              const Icon(Icons.watch_later_outlined, size: 10),
                              const SizedBox(width: 2),
                              _displayHours
                                  ? Text("$hours:$minutes")
                                  : Text(
                                      "${details["runtime"].toString()} min"),
                            ],
                          ),
                          Row(
                            children: [
                              const Icon(Icons.star, size: 10),
                              const SizedBox(width: 2),
                              Text(details["vote_average"].toString()),
                            ],
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ],
            ),
            stretchModes: const [
              StretchMode.zoomBackground,
              StretchMode.blurBackground,
            ],
          ),
        ),
        Opacity(
          opacity: _titleOpacity,
          child: ClipRect(
            child: BackdropFilter(
              filter: ImageFilter.blur(sigmaX: 7, sigmaY: 7),
              child: Container(
                color: Colors.transparent,
              ),
            ),
          ),
        ),
      ],
    );

    return Scaffold(
      body: CustomScrollView(
        controller: _scrollController,
        slivers: [
          SliverAppBar(
            actions: [
              IconButton(
                icon: const Icon(Icons.push_pin),
                onPressed: () {},
              ),
              IconButton(
                icon: const Icon(Icons.share),
                onPressed: () {},
              ),
            ],
            backgroundColor:
                Theme.of(context).colorScheme.background.withAlpha(200),
            title: Text(
              details["title"] as String,
              style: Theme.of(context)
                  .textTheme
                  .headlineSmall
                  ?.copyWith(color: Colors.white.withOpacity(_titleOpacity)),
            ),
            expandedHeight: 350,
            pinned: true,
            stretch: true,
            flexibleSpace: flexibleSpace,
          ),
          SliverPadding(
            padding: const EdgeInsets.only(bottom: 50),
            sliver: SliverToBoxAdapter(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const SizedBox(height: 10),
                  Padding(
                    padding: const EdgeInsets.only(left: 10),
                    child: Text("Summary",
                        style: Theme.of(context).textTheme.headlineSmall),
                  ),
                  Padding(
                    padding: const EdgeInsets.all(10),
                    child: Text(
                      details["overview"] as String,
                      style: Theme.of(context).textTheme.bodyLarge,
                    ),
                  ),
                  const SizedBox(height: 10),
                  Padding(
                    padding: const EdgeInsets.only(left: 10),
                    child: Text("Cast",
                        style: Theme.of(context).textTheme.headlineSmall),
                  ),
                  buildCredits(context, (details["credits"] as Map)["cast"]),
                  const SizedBox(height: 10),
                  Padding(
                    padding: const EdgeInsets.only(left: 10),
                    child: Text("Crew",
                        style: Theme.of(context).textTheme.headlineSmall),
                  ),
                  buildCredits(context, (details["credits"] as Map)["crew"]),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
